[package]
name = "coins"
version = "0.0.0"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives", subdir = "initia_stdlib", rev = "main" }

[addresses]
std =  "0x1"
your_address = "_"

[dev-addresses]
your_address = "0x2"