[package]
name = "basic_coin"
version = "0.0.0"

[addresses]
initia_std = "0x1"
std = "0x1"
your_address = "0x7c2a98d9bf4d13e96e06fa4b4bdf4b9ac5c7c17b"

[dev-addresses]
your_address = "0x2"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/initiavm.git", subdir = "crates/../precompile/modules/initia_stdlib", rev = "main" }